<a href="https://colab.research.google.com/github/shiva-sharma05/pandas-assignment/blob/main/Pandas_2_%26_3_Assign_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Pandas Final Assignment (Class 2 + Class 3)

### Topics Covered
- head()
- tail()
- info()
- shape
- dtypes
- loc
- iloc
- rename()
- set_index()
- reset_index()
- isnull()
- fillna()
- astype()
- replace()
- drop()
- duplicated()
- drop_duplicates()

### Instructions
- Use Pandas in every question.
- Write code in the blank code cell below each question.
- Print the required output.


# Q1. Display First Rows

## Problem Statement
Create the following DataFrame:

| Name | Age |
|------|-----|
| Aman | 21 |
| Rahul | 22 |
| Neha | 20 |
| Priya | 23 |
| Ravi | 24 |

Display the first 3 rows using `head()`.

## Sample Output
```python
First 3 rows of DataFrame
```

In [1]:
import pandas as pd
import numpy as np
d = pd.DataFrame({
    'name' : ['aman','rahul','neha','priya','ravi'] ,
    'age' : [21,22,20,23,24]
})
d.head(3)

    name  age
0   aman   21
1  rahul   22
2   neha   20


# Q2. Display Last Rows

## Problem Statement
Create a DataFrame containing 6 student records.

Display the last 2 rows using `tail()`.

## Sample Output
```python
Last 2 rows of DataFrame
```

In [ ]:
d.tail(2)

    name  age
3  priya   23
4   ravi   24


# Q3. Check DataFrame Information

## Problem Statement
Create a DataFrame containing:

```python
Name = ["Aman","Rahul","Neha"]
Marks = [80,75,90]
```

Display DataFrame information using `info()`.

## Sample Output
```python
<class 'pandas.core.frame.DataFrame'>
...
```

In [ ]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes


# Q4. Shape and Data Types

## Problem Statement
Create a DataFrame with:

```python
Name
Age
City
```

Print:
- Shape
- Data Types

## Sample Output
```python
(3,3)
object
int64
```

In [ ]:
df = pd.DataFrame({
    'name' : ['shiva','rishi' ,'sachin'],
    'age' : [20,21,22],
    'city' : ['rewa', 'satna' , 'sidhi']
})
print(df.shape)
print(df.dtypes)

(3, 3)
name    object
age      int64
city    object
dtype: object


# Q5. Select Data using loc

## Problem Statement
Create a DataFrame with Name, Age and City.

Using `loc`, display the Name and City of the first row.

## Sample Output
```python
Name    Aman
City    Bhopal
```

In [ ]:
d = pd.DataFrame({
    'name' : ['shiva','rishi' ,'sachin'],
    'city' : ['rewa', 'satna' , 'sidhi']
})
print(d.loc[0])

name    shiva
city     rewa
Name: 0, dtype: object


# Q6. Select Data using iloc

## Problem Statement
Create a DataFrame with at least 4 rows.

Using `iloc`, print:
- Second row
- First two columns

## Sample Output
```python
Selected row values
```

In [ ]:
d = pd.DataFrame({
    'name' : ['shiva','rishi' ,'sachin','ajay'],
    'age' : [20,21,22,23],
    'city' : ['rewa', 'satna' , 'sidhi','maihar']
})
print(d.iloc[1])
print(d.iloc[:, :2])

name    rishi
age        21
city    satna
Name: 1, dtype: object
     name  age
0   shiva   20
1   rishi   21
2  sachin   22
3    ajay   23


# Q7. Rename a Column

## Problem Statement
Create a DataFrame:

```python
Name
Marks
```

Rename column `Marks` to `Score`.

## Sample Output
```python
Name  Score
```

In [ ]:
d = pd.DataFrame({
    'name' : ['shiva','rishi' ,'sachin'],
    'marks' : [90,94,92]
})
d.rename(columns={'marks' : 'score'})

     name  score
0   shiva     90
1   rishi     94
2  sachin     92


# Q8. Handle Missing Values

## Problem Statement
Create a DataFrame:

```python
Name = ["Aman", None, "Neha"]
Marks = [80, 75, None]
```

Fill missing values using `fillna()`.

## Sample Output
```python
Missing values replaced
```

In [ ]:
d = pd.DataFrame({
    'Name' : ["Aman", None, "Neha"],
    'Marks' : [80, 75, None]
})
d['Name'] = d['Name'].fillna('unknown')
d['Marks'] = d['Marks'].fillna(0)
print(d)

      Name  Marks
0     Aman   80.0
1  unknown   75.0
2     Neha    0.0


# Q9. Replace Values

## Problem Statement
Create a DataFrame:

```python
City = ["BPL", "IND", "BPL"]
```

Replace:
- BPL → Bhopal
- IND → Indore

## Sample Output
```python
Bhopal
Indore
Bhopal
```

In [3]:
df = pd.DataFrame({
    'city' : ["BPL", "IND", "BPL"]
})
df.replace({'BPL' : 'Bhopal' , 'IND' : 'Indore'})

     city
0  Bhopal
1  Indore
2  Bhopal


# Q10. Remove Duplicate Records

## Problem Statement
Create a DataFrame:

```python
Name = ["Aman","Rahul","Aman","Neha"]
```

Check duplicate rows using `duplicated()` and remove them using `drop_duplicates()`.

## Sample Output
```python
Aman
Rahul
Neha
```

In [9]:
df = pd.DataFrame({
     'name' : ["Aman","Rahul","Aman","Neha"]
})
df = df.drop_duplicates()
df

    name
0   Aman
1  Rahul
3   Neha

In [ ]:
|