<a href="https://colab.research.google.com/github/shiva-sharma05/pandas-assignment/blob/main/pandas_class4_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Pandas Class 4 Assignment


# Q1. Select Single Column

## Problem Statement
Create a DataFrame and display only the Name column.

## Sample Input
```python
Name, Age
```

## Sample Output
```python
Only Name column
```

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Raj', 'Amit', 'Neha', 'Priya'],
    'Age': [22, 24, 21, 23],
    'Marks': [80, 75, 90, 85],
    'city' : ['bhopal' , 'rewa' , 'indore' , 'bhopal']
})

print(df.columns)

Index(['Name', 'Age', 'Marks', 'city'], dtype='object')


# Q2. Select Multiple Columns

## Problem Statement
Display Name and Marks columns from a DataFrame.

## Sample Input
```python
Name, Marks
```

## Sample Output
```python
Selected columns
```

In [ ]:
print(df[['Name', 'Marks']])

    Name  Marks
0    Raj     80
1   Amit     75
2   Neha     90
3  Priya     85


# Q3. Filter Students

## Problem Statement
Display students with Marks greater than 80.

## Sample Input
```python
Marks > 80
```

## Sample Output
```python
Filtered rows
```

In [ ]:
df['Marks'][df['Marks'] > 80]

2    90
3    85
Name: Marks, dtype: int64


# Q4. Filter by City

## Problem Statement
Display students belonging to Bhopal.

## Sample Input
```python
City = Bhopal
```

## Sample Output
```python
Matching rows
```

In [ ]:
df[df['city'] == 'bhopal']

    Name  Age  Marks    city
0    Raj   22     80  bhopal
3  Priya   23     85  bhopal


# Q5. Find Maximum Marks

## Problem Statement
Find the highest marks from a DataFrame.

## Sample Input
```python
Marks column
```

## Sample Output
```python
Highest value
```

In [ ]:
df['Marks'].max()

90


# Q6. Find Minimum Age

## Problem Statement
Find the minimum age.

## Sample Input
```python
Age column
```

## Sample Output
```python
Minimum age
```

In [ ]:
df['Age'].min()

21


# Q7. Sort Data

## Problem Statement
Sort students by Marks.

## Sample Input
```python
Marks column
```

## Sample Output
```python
Sorted DataFrame
```

In [ ]:
df['Marks'].sort_values()

1    75
0    80
3    85
2    90
Name: Marks, dtype: int64


# Q8. Value Counts

## Problem Statement
Count occurrences of each city.

## Sample Input
```python
City column
```

## Sample Output
```python
Frequency count
```

In [ ]:
df['city'].value_counts()

city
bhopal    2
rewa      1
indore    1
Name: count, dtype: int64


# Q9. Group By City

## Problem Statement
Find average marks city-wise.

## Sample Input
```python
City and Marks
```

## Sample Output
```python
Grouped result
```

In [ ]:
df.groupby('city')['Marks'].mean()

city
bhopal    82.5
indore    90.0
rewa      75.0
Name: Marks, dtype: float64


# Q10. Multiple Conditions

## Problem Statement
Display students with Marks > 70 and Age > 20.

## Sample Input
```python
Marks and Age
```

## Sample Output
```python
Filtered rows
```

In [ ]:
df[(df['Marks'] > 70) & (df['Age'] > 20)]

    Name  Age  Marks    city
0    Raj   22     80  bhopal
1   Amit   24     75    rewa
2   Neha   21     90  indore
3  Priya   23     85  bhopal